### ISSUE TITLE
Can you please add some docs?

### ISSUE THREAD

**Issue by b4oshany** [danpoland/pyramid-restful-framework#9]

**Comment by aortyl** [comment]
+1

**Comment by danpoland** [comment]
I will try to throw together some docs to demonstrate basic usage of the framework soon.

**Comment by danpoland** [comment]
Sorry for the delay but I am just about finished with the docs. I should have the last pages written and everything cleaned up by the end of the week. Until then you can find the WIP docs here: http://pyramid-restful-framework.readthedocs.io/en/docs/

**Comment by danpoland** [comment]
The docs are live at: http://pyramid-restful-framework.readthedocs.io/en/latest/
